//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class ___VARIABLE_productName:identifier___Interactor {
    
    // MARK: - Properties
    var presenter: ___VARIABLE_productName:identifier___Presentable?
    var router: ___VARIABLE_productName:identifier___Routing?
    
}

// MARK: - ___VARIABLE_productName:identifier___Interactable
extension ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___Interactable {
    
}
