//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

protocol I___VARIABLE_productName:identifier___View: AnyObject {

}

class ___VARIABLE_productName:identifier___View: UIView {
    
    // MARK: - Properties
    weak var delegate: I___VARIABLE_productName:identifier___View?
    
    // MARK: - Initialization
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupUI()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

// MARK: - UI Setup
extension ___VARIABLE_productName:identifier___View {
    private func setupUI() {
        self.backgroundColor = .white
        
    }
}
