//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class ___VARIABLE_productName:identifier___Presenter {
    
    // MARK: - Properties
    weak var viewController: ___VARIABLE_productName:identifier___PresenterOutput?
    
}

// MARK: - ___VARIABLE_productName:identifier___Presentable
extension ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___Presentable {
    
}
