//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import Foundation

// MARK: - ViewController
protocol ___VARIABLE_productName:identifier___PresenterOutput: AnyObject {
    
}

// MARK: - Interactable
protocol ___VARIABLE_productName:identifier___Interactable: AnyObject {
    
}

// MARK: - Presentable
protocol ___VARIABLE_productName:identifier___Presentable: AnyObject {

}

// MARK: - Routing
protocol ___VARIABLE_productName:identifier___Routing: AnyObject {

}
