//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ibrokhim Movlonov

import UIKit

class ___VARIABLE_sceneName___Worker {
    
    // MARK: - Public
    func doSomeWork() {
        
    }
    
//    func doSomeOtherWork() {
//
//    }
    
}
